data:
    yaml_path: ./yolo/dataset/data.yaml
    test_image: ./yolo/dataset/images/test/hurricane-florence_00000028_post_disaster.png

model:
    name: yolov8s.pt
    input_size: [640, 640]

training:
    batch_size: 8
    epochs: 10
    run_name: building_damage_model
