data:
  yaml_path: /path/to/your/data.yaml
  test_image: /path/to/your/test/image.png

model:
  name: yolov8s.pt
  input_size: [640, 640]

training:
  batch_size: 8
  epochs: 100
  run_name: building_damage_model
