data:
  original_images_path: data/original_images
  processed_images_path: data/processed_images
  augmented_images_path: data/augmented_images
  train: train/images
  val: valid/images
  test: test/images
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  nc: 5
  names: ['full_damage', 'high_damage', 'low_damage', 'medium_damage', 'plane']

model:
  name: yolov8s
  input_size: [640, 640]
  num_classes: 5

training:
  batch_size: 4
  epochs: 30
  learning_rate: 0.01
  optimizer: AdamW

preprocessing:
  target_size: [608, 608]

augmentation:
  horizontal_flip: true
  vertical_flip: false
  rotation_range: 15
  brightness_range: [0.8, 1.2]
  zoom_range: [0.8, 1.2]
  num_augmented_images: 100

roboflow:
  workspace: simone-v3xxq
  project: damaged-buildings-kusty
  version: 1
  license: MIT
  url: https://universe.roboflow.com/simone-v3xxq/damaged-buildings-kusty/dataset/1